version: '2'
services:
  securitiesservice:
    build: .
    links:
      - redis
    environment:
      - REDIS_PORT_6379_TCP_ADDR=redis
      - REDIS_PORT_6379_TCP_PORT=6379
    ports:
      - "8080:8080"
  redis:
    image: redis
    volumes:
      - "/root/redis:/data"
    ports:
      - "6379:6379"
