version: '2'
services:
  securitiespopulater:
    build: .
    links:
      - redis
    environment:
      "REDIS_PORT_6379_TCP_ADDR": "redis"
      "REDIS_PORT_6379_TCP_PORT": "6379"
  redis:
    image: redis
    volumes:
      - "/root/redis:/data"
    ports:
      - "6379:6379"
